import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import UserProvider from "./UserContext";


const poppins = Poppins({ 
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata = {
  title: "Vortly-NEXT.JS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en">
      <body className={poppins.className}>
        <UserProvider>
        <Header/>
        <main>
        {children}
        </main>
        <Footer/>
        </UserProvider>
      </body>
    </html>
    
  );
}
